name: release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'firmwere_srcs/'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAG=`date +"%Y%m%d-%H%M%S"`
          export RELEASE_FILE=firmware-v${TAG}.zip
          zip ${RELEASE_FILE} -r ./firmwere_srcs/JoySmall20/
          gh release create ${TAG} ${RELEASE_FILE}